const path = require("path");
const CopyWebpackPlugin = require("copy-webpack-plugin");

module.exports = {
  mode: 'development',
  entry: "./src/main.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  plugins: [
    new CopyWebpackPlugin([{ from: "./src/index.html", to: "index.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/homepage.html", to: "homepage.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/about-us.html", to: "about-us.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/contact.html", to: "contact.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/awareness.html", to: "awareness.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/donor-registration.html", to: "donor-registration.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/donor-pledge.html", to: "donor-pledge.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/patient-registration.html", to: "patient-registration.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/verify-pledges.html", to: "verify-pledges.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/view-donors.html", to: "view-donors.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/view-pledges.html", to: "view-pledges.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/view-patients.html", to: "view-patients.html" }]),
    new CopyWebpackPlugin([{ from: "./src/html/transplant-matching.html", to: "transplant-matching.html" }]),
    new CopyWebpackPlugin([{ from: "./src/css/bootstrap.css", to: "css/bootstrap.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/styles.css", to: "css/styles.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/style-home.css", to: "css/style-home.css" }]),
    new CopyWebpackPlugin([{ from: "./src/css/fontawesome-all.css", to: "css/fontawesome-all.css" }]),
    new CopyWebpackPlugin([{ from: "./src/images/logopng.png", to: "images/logopng.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/icon.svg", to: "images/icon.svg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/logopng.png", to: "images/logopng.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/logopng.png", to: "images/logopng.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/logopng", to: "images/logopng.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/header-image-new.png", to: "images/header-image-new.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/logopng.png", to: "images/logopng.png" }]),
    new CopyWebpackPlugin([{ from: "./src/images/icon.svg", to: "images/icon.svg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/icon.svg", to: "images/icon.svg"}]),
    new CopyWebpackPlugin([{ from: "./src/images/donation-icon.svg", to: "images/donation-icon.svg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/transplant-icon.svg", to: "images/transplant-icon.svg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/waiting-list-icon.svg", to: "images/waiting-list-icon.svg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/mail-icon.svg", to: "images/mail-icon.svg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sid.jpeg", to: "images/sid.jpeg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/riyaz.jpeg", to: "images/riyaz.jpeg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/sayan.jpg", to: "images/sayan.jpg" }]),
    new CopyWebpackPlugin([{ from: "./src/images/Roshni.jpeg", to: "images/Roshni.jpeg" }]),    
  ],
  devServer: { contentBase: path.join(__dirname, "dist"), compress: true },
};